// =====================================================================
// INTELLITASK — Dummy Data Configuration
// =====================================================================
// Toggle DUMMY_DATA to switch data source:
//   true  → Use hardcoded Indian-named mock data (no backend required)
//   false → All hooks fetch from backend API (http://localhost:5000/api)
// =====================================================================
export const DUMMY_DATA = true

// ─── Users ───────────────────────────────────────────────────────────
export const dummyUsers = [
  {
    id: "u1",
    name: "Arjun Sharma",
    email: "admin1@example.com",
    company: "IntelliTask Inc.",
    role: "admin" as const,
    status: "Online" as const,
  },
  {
    id: "u2",
    name: "Priya Patel",
    email: "manager1@example.com",
    company: "IntelliTask Inc.",
    role: "manager" as const,
    status: "Online" as const,
  },
  {
    id: "u3",
    name: "Rahul Mehta",
    email: "member1@example.com",
    company: "IntelliTask Inc.",
    role: "member" as const,
    status: "Online" as const,
  },
  {
    id: "u4",
    name: "Sneha Iyer",
    email: "sneha@example.com",
    company: "IntelliTask Inc.",
    role: "member" as const,
    status: "Away" as const,
  },
  {
    id: "u5",
    name: "Vikram Nair",
    email: "vikram@example.com",
    company: "IntelliTask Inc.",
    role: "member" as const,
    status: "Busy" as const,
  },
  {
    id: "u6",
    name: "Ananya Krishnan",
    email: "ananya@example.com",
    company: "IntelliTask Inc.",
    role: "member" as const,
    status: "Online" as const,
  },
  {
    id: "u7",
    name: "Rohan Gupta",
    email: "rohan@example.com",
    company: "IntelliTask Inc.",
    role: "manager" as const,
    status: "Away" as const,
  },
  {
    id: "u8",
    name: "Kavya Reddy",
    email: "kavya@example.com",
    company: "IntelliTask Inc.",
    role: "member" as const,
    status: "Online" as const,
  },
  {
    id: "u9",
    name: "Aditya Verma",
    email: "aditya@example.com",
    company: "IntelliTask Inc.",
    role: "member" as const,
    status: "Busy" as const,
  },
  {
    id: "u10",
    name: "Pooja Desai",
    email: "pooja@example.com",
    company: "IntelliTask Inc.",
    role: "member" as const,
    status: "Online" as const,
  },
]

// ─── Login credentials map (for DUMMY_DATA auth) ─────────────────────
export const dummyCredentials: Record<string, { password: string; userId: string }> = {
  "admin1@example.com": { password: "admin-1", userId: "u1" },
  "manager1@example.com": { password: "manager-1", userId: "u2" },
  "member1@example.com": { password: "member-1", userId: "u3" },
}

// ─── Workspaces ───────────────────────────────────────────────────────
export const dummyWorkspaces = [
  {
    id: "ws1",
    name: "Product Development",
    description: "Main product engineering workspace",
    template: "engineering",
    visibility: "private" as const,
    createdAt: "2026-01-10",
    memberCount: 8,
    isOwner: true,
  },
  {
    id: "ws2",
    name: "Design & UX",
    description: "Design system and user experience",
    template: "design",
    visibility: "private" as const,
    createdAt: "2026-01-15",
    memberCount: 5,
    isOwner: false,
  },
  {
    id: "ws3",
    name: "Marketing Sprint",
    description: "Q2 marketing campaigns and growth",
    template: "marketing",
    visibility: "public" as const,
    createdAt: "2026-02-01",
    memberCount: 4,
    isOwner: false,
  },
]

// ─── Tasks ────────────────────────────────────────────────────────────
export const dummyTasks = [
  {
    id: "t1",
    title: "Redesign homepage hero section",
    description: "Update the hero with new brand guidelines, improved CTA, and animated gradient",
    status: "in-progress" as const,
    priority: "high" as const,
    assigneeId: "u3",
    assigneeName: "Rahul Mehta",
    assigneeInitials: "RM",
    creatorId: "u2",
    creatorName: "Priya Patel",
    workspaceId: "ws1",
    dueDate: "2026-05-10",
    createdAt: "2026-04-28",
    updatedAt: "2026-05-03",
    comments: [
      {
        id: "c1",
        taskId: "t1",
        userId: "u3",
        userName: "Rahul Mehta",
        userInitials: "RM",
        content: "Working on the responsive breakpoints now, looks great on mobile",
        createdAt: "2026-05-03",
      },
    ],
    attachments: [],
    tags: ["frontend", "design", "ui"],
    estimatedHours: 12,
    actualHours: 7,
    progress: 65,
  },
  {
    id: "t2",
    title: "Implement JWT authentication",
    description: "Add JWT token-based auth to the backend API with refresh token and blacklist support",
    status: "todo" as const,
    priority: "urgent" as const,
    assigneeId: "u5",
    assigneeName: "Vikram Nair",
    assigneeInitials: "VN",
    creatorId: "u2",
    creatorName: "Priya Patel",
    workspaceId: "ws1",
    dueDate: "2026-05-08",
    createdAt: "2026-04-29",
    updatedAt: "2026-04-29",
    comments: [],
    attachments: [],
    tags: ["backend", "security", "auth"],
    estimatedHours: 16,
    actualHours: 0,
    progress: 0,
  },
  {
    id: "t3",
    title: "Database query optimisation",
    description: "Optimise slow MongoDB aggregation queries affecting dashboard load time by 40%",
    status: "stuck" as const,
    priority: "high" as const,
    assigneeId: "u4",
    assigneeName: "Sneha Iyer",
    assigneeInitials: "SI",
    creatorId: "u1",
    creatorName: "Arjun Sharma",
    workspaceId: "ws1",
    dueDate: "2026-05-06",
    createdAt: "2026-04-25",
    updatedAt: "2026-05-02",
    comments: [
      {
        id: "c2",
        taskId: "t3",
        userId: "u4",
        userName: "Sneha Iyer",
        userInitials: "SI",
        content: "Blocked — missing index documentation and prod DB access",
        createdAt: "2026-05-02",
      },
    ],
    attachments: [],
    tags: ["backend", "database", "performance"],
    estimatedHours: 8,
    actualHours: 5,
    progress: 35,
  },
  {
    id: "t4",
    title: "Mobile app onboarding flow",
    description: "Design and implement 5-screen onboarding with Lottie animations",
    status: "done" as const,
    priority: "medium" as const,
    assigneeId: "u6",
    assigneeName: "Ananya Krishnan",
    assigneeInitials: "AK",
    creatorId: "u2",
    creatorName: "Priya Patel",
    workspaceId: "ws2",
    dueDate: "2026-05-01",
    createdAt: "2026-04-18",
    updatedAt: "2026-04-30",
    comments: [],
    attachments: [],
    tags: ["mobile", "ux", "design"],
    estimatedHours: 20,
    actualHours: 18,
    progress: 100,
  },
  {
    id: "t5",
    title: "Write OpenAPI documentation",
    description: "Document all REST endpoints using OpenAPI 3.1 specification with examples",
    status: "todo" as const,
    priority: "medium" as const,
    assigneeId: "u8",
    assigneeName: "Kavya Reddy",
    assigneeInitials: "KR",
    creatorId: "u1",
    creatorName: "Arjun Sharma",
    workspaceId: "ws1",
    dueDate: "2026-05-15",
    createdAt: "2026-04-30",
    updatedAt: "2026-04-30",
    comments: [],
    attachments: [],
    tags: ["documentation", "api"],
    estimatedHours: 10,
    actualHours: 0,
    progress: 0,
  },
  {
    id: "t6",
    title: "Setup CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing, linting and deployment to staging",
    status: "in-progress" as const,
    priority: "high" as const,
    assigneeId: "u5",
    assigneeName: "Vikram Nair",
    assigneeInitials: "VN",
    creatorId: "u1",
    creatorName: "Arjun Sharma",
    workspaceId: "ws1",
    dueDate: "2026-05-12",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-04",
    comments: [],
    attachments: [],
    tags: ["devops", "ci-cd", "automation"],
    estimatedHours: 14,
    actualHours: 6,
    progress: 45,
  },
  {
    id: "t7",
    title: "User behaviour analytics integration",
    description: "Integrate Mixpanel for funnel analysis and user retention tracking",
    status: "todo" as const,
    priority: "low" as const,
    assigneeId: "u3",
    assigneeName: "Rahul Mehta",
    assigneeInitials: "RM",
    creatorId: "u7",
    creatorName: "Rohan Gupta",
    workspaceId: "ws3",
    dueDate: "2026-05-20",
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    comments: [],
    attachments: [],
    tags: ["analytics", "marketing"],
    estimatedHours: 8,
    actualHours: 0,
    progress: 0,
  },
  {
    id: "t8",
    title: "Performance audit & Core Web Vitals",
    description: "Run Lighthouse audit and fix all performance bottlenecks to achieve LCP < 2s",
    status: "done" as const,
    priority: "medium" as const,
    assigneeId: "u6",
    assigneeName: "Ananya Krishnan",
    assigneeInitials: "AK",
    creatorId: "u2",
    creatorName: "Priya Patel",
    workspaceId: "ws1",
    dueDate: "2026-04-28",
    createdAt: "2026-04-20",
    updatedAt: "2026-04-27",
    comments: [],
    attachments: [],
    tags: ["performance", "frontend"],
    estimatedHours: 10,
    actualHours: 9,
    progress: 100,
  },
  {
    id: "t9",
    title: "Email notification system",
    description: "Build transactional email service using Resend for task assignments and deadlines",
    status: "in-progress" as const,
    priority: "medium" as const,
    assigneeId: "u9",
    assigneeName: "Aditya Verma",
    assigneeInitials: "AV",
    creatorId: "u1",
    creatorName: "Arjun Sharma",
    workspaceId: "ws1",
    dueDate: "2026-05-14",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-04",
    comments: [],
    attachments: [],
    tags: ["backend", "notifications", "email"],
    estimatedHours: 12,
    actualHours: 4,
    progress: 30,
  },
  {
    id: "t10",
    title: "Accessibility (WCAG 2.1) audit",
    description: "Audit entire application for WCAG 2.1 AA compliance and fix all critical issues",
    status: "todo" as const,
    priority: "low" as const,
    assigneeId: "u10",
    assigneeName: "Pooja Desai",
    assigneeInitials: "PD",
    creatorId: "u2",
    creatorName: "Priya Patel",
    workspaceId: "ws2",
    dueDate: "2026-05-22",
    createdAt: "2026-05-04",
    updatedAt: "2026-05-04",
    comments: [],
    attachments: [],
    tags: ["accessibility", "frontend", "ux"],
    estimatedHours: 6,
    actualHours: 0,
    progress: 0,
  },
]

// ─── Activities ───────────────────────────────────────────────────────
export const dummyActivities = [
  {
    id: "a1",
    userId: "u6",
    userName: "Ananya Krishnan",
    userInitials: "AK",
    action: "completed",
    taskTitle: "Mobile app onboarding flow",
    time: "20 minutes ago",
    type: "completed" as const,
    color: "bg-emerald-500",
  },
  {
    id: "a2",
    userId: "u3",
    userName: "Rahul Mehta",
    userInitials: "RM",
    action: "updated",
    taskTitle: "Redesign homepage hero section",
    time: "1 hour ago",
    type: "updated" as const,
    color: "bg-indigo-500",
  },
  {
    id: "a3",
    userId: "u5",
    userName: "Vikram Nair",
    userInitials: "VN",
    action: "started",
    taskTitle: "Setup CI/CD pipeline",
    time: "2 hours ago",
    type: "created" as const,
    color: "bg-violet-500",
  },
  {
    id: "a4",
    userId: "u4",
    userName: "Sneha Iyer",
    userInitials: "SI",
    action: "commented on",
    taskTitle: "Database query optimisation",
    time: "3 hours ago",
    type: "commented" as const,
    color: "bg-amber-500",
  },
  {
    id: "a5",
    userId: "u2",
    userName: "Priya Patel",
    userInitials: "PP",
    action: "assigned",
    taskTitle: "Implement JWT authentication",
    time: "Yesterday",
    type: "created" as const,
    color: "bg-blue-500",
  },
  {
    id: "a6",
    userId: "u9",
    userName: "Aditya Verma",
    userInitials: "AV",
    action: "started",
    taskTitle: "Email notification system",
    time: "Yesterday",
    type: "created" as const,
    color: "bg-rose-500",
  },
]

// ─── Notifications ────────────────────────────────────────────────────
export const dummyNotifications = [
  {
    id: "n1",
    title: "Task overdue",
    message: "Database query optimisation is past its due date",
    type: "deadline" as const,
    priority: "high" as const,
    isRead: false,
    createdAt: "2026-05-05",
  },
  {
    id: "n2",
    title: "Assigned to you",
    message: "Priya Patel assigned 'OpenAPI Documentation' to you",
    type: "assignment" as const,
    priority: "medium" as const,
    isRead: false,
    createdAt: "2026-05-04",
  },
  {
    id: "n3",
    title: "Task completed",
    message: "Ananya Krishnan completed 'Mobile app onboarding flow'",
    type: "system" as const,
    priority: "low" as const,
    isRead: true,
    createdAt: "2026-05-04",
  },
  {
    id: "n4",
    title: "Stuck task alert",
    message: "AI detected: 'Database query optimisation' has been stuck for 3 days",
    type: "system" as const,
    priority: "high" as const,
    isRead: false,
    createdAt: "2026-05-05",
  },
]

// ─── Member Performance (for analytics) ──────────────────────────────
export const dummyMemberPerformance = [
  {
    id: "u6",
    name: "Ananya Krishnan",
    role: "member",
    avatar: "AK",
    tasksCompleted: 18,
    tasksInProgress: 1,
    efficiency: 96,
    avgCompletionDays: 1.8,
    trend: "+8%" as const,
  },
  {
    id: "u3",
    name: "Rahul Mehta",
    role: "member",
    avatar: "RM",
    tasksCompleted: 14,
    tasksInProgress: 2,
    efficiency: 92,
    avgCompletionDays: 2.1,
    trend: "+5%" as const,
  },
  {
    id: "u8",
    name: "Kavya Reddy",
    role: "member",
    avatar: "KR",
    tasksCompleted: 13,
    tasksInProgress: 1,
    efficiency: 88,
    avgCompletionDays: 2.3,
    trend: "+3%" as const,
  },
  {
    id: "u5",
    name: "Vikram Nair",
    role: "member",
    avatar: "VN",
    tasksCompleted: 11,
    tasksInProgress: 2,
    efficiency: 78,
    avgCompletionDays: 2.9,
    trend: "-2%" as const,
  },
  {
    id: "u4",
    name: "Sneha Iyer",
    role: "member",
    avatar: "SI",
    tasksCompleted: 9,
    tasksInProgress: 1,
    efficiency: 71,
    avgCompletionDays: 3.4,
    trend: "+1%" as const,
  },
  {
    id: "u9",
    name: "Aditya Verma",
    role: "member",
    avatar: "AV",
    tasksCompleted: 7,
    tasksInProgress: 1,
    efficiency: 82,
    avgCompletionDays: 2.6,
    trend: "+12%" as const,
  },
]

// ─── Productivity Trend (7-day) ───────────────────────────────────────
export const dummyProductivityTrend = [
  { date: "Apr 29", completed: 4, created: 6, efficiency: 80 },
  { date: "Apr 30", completed: 7, created: 5, efficiency: 85 },
  { date: "May 01", completed: 5, created: 8, efficiency: 72 },
  { date: "May 02", completed: 9, created: 4, efficiency: 91 },
  { date: "May 03", completed: 6, created: 7, efficiency: 78 },
  { date: "May 04", completed: 11, created: 6, efficiency: 88 },
  { date: "May 05", completed: 8, created: 5, efficiency: 94 },
]

// ─── Online Presence ──────────────────────────────────────────────────
export const dummyPresence = [
  { id: "u1", name: "Arjun Sharma", initials: "AS", status: "online" as const, currentPage: "Admin Dashboard" },
  { id: "u2", name: "Priya Patel", initials: "PP", status: "online" as const, currentPage: "Team Overview" },
  { id: "u3", name: "Rahul Mehta", initials: "RM", status: "online" as const, currentPage: "Task: Hero Redesign" },
  { id: "u6", name: "Ananya Krishnan", initials: "AK", status: "away" as const, currentPage: "Design Workspace" },
  { id: "u5", name: "Vikram Nair", initials: "VN", status: "busy" as const, currentPage: "CI/CD Setup" },
  { id: "u4", name: "Sneha Iyer", initials: "SI", status: "offline" as const, currentPage: "Last seen 2h ago" },
]
